services:
  dynamodb_local:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - 8000:8000
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data:
